version: '3'

services:
  portfolio_svelte:
    container_name: 'portfolio-svelte'
    restart: unless-stopped
    build:
      context: /home/sachinda
      dockerfile: ./repos/portfolio-svelte/dockerfile
    ports:
      - '3100:3100'
